# docker-compose.yml - VS Code Docs 기능을 위한 Docker 설정
version: '3'

services:
  vscode-docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"  # MCP 서버 포트
    volumes:
      - ./data:/app/data  # 데이터 영속성
    environment:
      - SENTENCE_TRANSFORMERS_HOME=/app/data/models
    restart: unless-stopped